spring:
  security:
    user:
      name: blurooo
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/springDemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456